images:
  - crds-artifact
  - jupyternetes-pods-operator
  - jupyternetes-pvcs-operator
  - python-libraries-artifact
  - jupyternetes-hub
  - jupyternetes-podstatus-operator
  - docs-artifact
  
platforms:
  - amd64
  #- arm64

helm_charts:
  - kadense
  - kadense-crds